- hosts: "all_cisco_ios"
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: USER
      password: PASS
      authorize: YES 
      auth_pass: CISCO_ENABLE_MODE_PASSWORD
  tasks:
    - name: "Config Cisco IOS switches"
      ios_command:
       commands:
         - show version
       provider: "{{ cli }}"
      register: ios_result
    - name: Result for Cisco IOS switches
      debug: var=ios_result.stdout_lines
